In [1]:
import qsimov as qs
import numpy as np

In [2]:
r = qs.QRegistry(2)
r.getState()

array([1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j])

In [3]:
r.densityMatrix()[:]

[[(1+0j), 0j, 0j, 0j], [0j, 0j, 0j, 0j], [0j, 0j, 0j, 0j], [0j, 0j, 0j, 0j]]

In [4]:
r.ket()@r.bra()

array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j]])

In [5]:
r.ket()

array([[1.+0.j],
       [0.+0.j],
       [0.+0.j],
       [0.+0.j]])

In [6]:
r.bra()

array([[1.-0.j, 0.-0.j, 0.-0.j, 0.-0.j]])

In [7]:
r.applyGate(qs.H(2))
r.getState()

array([0.5+0.j, 0.5+0.j, 0.5+0.j, 0.5+0.j])

In [8]:
r1 = qs.QRegistry(2)
r1.getState()
print(r1.vnEntropy(base=2))
print(r.vnEntropy(base=2))

0.49999999999999994
2.0


In [9]:
r.applyGate(qs.H(1), qs.I(1))
r.getState()

array([0.70710678+0.j, 0.70710678+0.j, 0.        +0.j, 0.        +0.j])

In [10]:
r_teleportacion = qs.QRegistry(2)
r_teleportacion.applyGate(qs.H(1), qs.I(1))
r_teleportacion.applyGate(qs.CNOT())
r_teleportacion.getState()

array([0.70710678+0.j, 0.        +0.j, 0.        +0.j, 0.70710678+0.j])

In [11]:
r_enviar = qs.QRegistry(1)
r_enviar.applyGate(qs.Rx(np.pi/16))
r_enviar.applyGate(qs.Rz(np.pi/4))
r_enviar.getState()

array([0.9194308 -0.38084071j, 0.03750954-0.09055603j])

In [12]:
r_all = qs.superposition(r_enviar, r_teleportacion)
r_all.getState()

array([0.65013575-0.26929505j, 0.        +0.j        ,
       0.        +0.j        , 0.65013575-0.26929505j,
       0.02652325-0.06403278j, 0.        +0.j        ,
       0.        +0.j        , 0.02652325-0.06403278j])

In [13]:
r_all.applyGate(qs.CNOT(),qs.I(1))
r_all.applyGate(qs.H(1),qs.I(2))
r_all.getState()

array([ 0.4597154 -0.19042035j,  0.01875477-0.04527801j,
        0.01875477-0.04527801j,  0.4597154 -0.19042035j,
        0.4597154 -0.19042035j, -0.01875477+0.04527801j,
       -0.01875477+0.04527801j,  0.4597154 -0.19042035j])

In [14]:
r_all.measure([1,1,0],remove=True)

[1, 1]

In [15]:
r_all.applyGate(qs.PauliX())
r_all.applyGate(qs.PauliZ())

In [16]:
r_all.getState()

array([0.9194308 -0.38084071j, 0.03750954-0.09055603j])

In [17]:
#Deutsch
r_deutsch = qs.QRegistry(2)
dqc = qs.QCircuit("Deutsch")
dqc.addLine(qs.H(1),qs.PauliX())
dqc.addLine(qs.I(1),qs.H(1))
dqc.addLine(qs.CNOT())
dqc.addLine(qs.H(1),qs.I(1))
dqc.addLine(qs.Measure([1,0]))
dqc.execute([0,0])[0].getState()

array([ 0.        +0.j,  0.        +0.j,  0.70710678+0.j, -0.70710678+0.j])